- name: Install required packages
  hosts: target
  become: yes
  vars:
    packages:
      - apache2
      - binutils
      - glibc
      - ksh
      - libaio
      - libXext
      - gcc
      - make
      - sysstat
      - unixODBC
      - mongodb
      - nodejs
      - grunt

  tasks:
    - apt: name="{{ item }}" state=present
      with_items: "{{ packages }}"
      ignore_errors: yes
      register: myoutput

    - debug: var=myoutput