- name: Create a EC2 instance
  hosts: localhost

  vars:
    - keypair: aws_devops
#    - aws_access_key:
#    - aws_secret_key:
    - instance_type: t2.micro
    - ami: ami-0261755bbcb8c4a84
    - region: us-east-1
    - vpc_subnet_id: subnet-0a96bc181333afae0

  tasks:
    - name: Create an EC2 Instance
      ec2:
        key_name: "{{ keypair }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: ansible-test-sg-public  # security group
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: true
        region: "{{ region }}"
        count: 1
        count_tag:
          Name: "Demo"
        instance_tags:
          Name: "Demo"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
      register: ec2

    - debug: var="{{ item['private_ip'] }}"
      with_items: "{{ ec2.instances }}"

    - name: Add all the web instances to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: webservers
        ansible_user: ubuntu
      with_items: "{{ ec2.instances }}"

    - name: Wait for ssh to come up
      wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=320 state=started
      with_items: "{{ ec2.instances }}"